name = "ITensorHandsOn"
authors = ["Miles Stoudenmire <mstoudenmire@flatironinstitute.org>", "Karl Pierce <kpierce@flatironinstitute.org>"]
version = "0.0.1"

[deps]
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"

[compat]
LinearMaps = "<3.11.2"